const SECOND_MS = 1000;
const MINUTE_SECONDS = 60;
const MINUTE_MS = MINUTE_SECONDS * SECOND_MS;

const PAYLINES = [
  [0, 0, 0, 0, 0],
  [1, 1, 1, 1, 1],
  [2, 2, 2, 2, 2],
  [0, 1, 2, 1, 0],
  [2, 1, 0, 1, 2],
  [0, 0, 1, 0, 0],
  [2, 2, 1, 2, 2],
  [1, 0, 0, 0, 1],
  [1, 2, 2, 2, 1],
  [0, 1, 1, 1, 0],
  [2, 1, 1, 1, 2],
  [1, 0, 1, 2, 1],
  [1, 2, 1, 0, 1],
  [0, 1, 0, 1, 0],
  [2, 1, 2, 1, 2],
  [0, 2, 0, 2, 0],
  [2, 0, 2, 0, 2],
  [0, 2, 2, 2, 0],
  [2, 0, 0, 0, 2],
  [1, 1, 0, 1, 1],
];

const SYMBOLS = [
  { id: "GPT5", label: "GPT-5", emoji: "🤖", weight: 6, payout: { 3: 8, 4: 22, 5: 80 } },
  { id: "CLAUDE", label: "Claude", emoji: "🧠", weight: 7, payout: { 3: 7, 4: 18, 5: 70 } },
  { id: "GEMINI", label: "Gemini", emoji: "♊", weight: 7, payout: { 3: 6, 4: 16, 5: 65 } },
  { id: "GROK", label: "Grok", emoji: "⚡", weight: 8, payout: { 3: 6, 4: 14, 5: 60 } },
  { id: "DISRUPTION", label: "Disruption", emoji: "📈", weight: 10, payout: { 3: 5, 4: 12, 5: 55 } },
  { id: "TEN_X", label: "10x Engineer", emoji: "🛠️", weight: 9, payout: { 3: 5, 4: 11, 5: 50 } },
  { id: "PIVOT", label: "Pivot", emoji: "🔁", weight: 9, payout: { 3: 4, 4: 10, 5: 45 } },
  { id: "AGI_SOON", label: "AGI Soon", emoji: "🛰️", weight: 8, payout: { 3: 4, 4: 9, 5: 40 } },
  { id: "HALLUCINATION", label: "Hallucination", emoji: "🌀", weight: 3, payout: { 3: 10, 4: 35, 5: 120 } },
  { id: "PROMPT", label: "Prompt", emoji: "📝", weight: 5, payout: { 3: 3, 4: 7, 5: 20 } },
];

const XP_TIERS = [
  { id: "BRONZE", label: "Bronze", minXp: 0 },
  { id: "SILVER", label: "Silver", minXp: 400 },
  { id: "GOLD", label: "Gold", minXp: 1000 },
  { id: "PLATINUM", label: "Platinum", minXp: 1800 },
  { id: "VIP", label: "VIP", minXp: 2800 },
];

const WIN_MESSAGES = [
  "You've achieved AGI... of profits.",
  "Your startup just pivoted into solvency.",
  "Disruption detected: bankroll now nonlinear.",
  "The board approved your hallucinated roadmap.",
  "10x engineer mode: enabled by luck.",
];

const CONFIG = {
  APP: {
    NAME: "AI Satire Slots",
    VERSION: "1.0.0",
  },
  SERVER: {
    DEFAULT_PORT: 8787,
    DEFAULT_ALLOWED_ORIGINS: ["http://localhost:8787"],
    JSON_LIMIT: "64kb",
  },
  SECURITY: {
    DEV_JWT_SECRET: "dev-only-replace-this-jwt-secret",
    JWT_EXPIRY_SECONDS: 15 * MINUTE_SECONDS,
    WEBSOCKET_RATE_LIMIT_PER_MINUTE: 30,
    WEBSOCKET_RATE_WINDOW_MS: MINUTE_MS,
    SIGNATURE_ALGORITHM: "sha256",
    FINGERPRINT_HASH_ALGORITHM: "sha256",
    CSP: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' ws: wss:; font-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none';",
    REQUEST_SIGNATURE_WINDOW_MS: 5 * MINUTE_MS,
  },
  SANITIZE: {
    MAX_STRING_LENGTH: 120,
    REPLACE_PATTERN: /[<>{}$\\]/g,
    REPLACE_WITH: "",
  },
  GAME: {
    GRID_ROWS: 3,
    GRID_REELS: 5,
    PAYLINES,
    RTP_TARGET: 0.96,
    BET_MIN: 0.1,
    BET_MAX: 10,
    BET_STEP: 0.1,
    BET_DEFAULT: 1,
    STARTING_BALANCE: 100,
    STARTING_JACKPOT_POOL: 1000,
    JACKPOT_CONTRIBUTION_RATE: 0.01,
    FREE_SPINS_AWARDED: 10,
    FREE_SPIN_MULTIPLIER: 2,
    CASCADE_MAX_STEPS: 5,
    NEAR_MISS_FREQUENCY: 0.22,
    TURBO_SPIN_MS: 1000,
    NORMAL_SPIN_MS: 2500,
    SPIN_FLOOR_MS: 2500,
    AUTOPLAY_MAX_SPINS: 50,
    REALITY_CHECK_INTERVAL_MS: 60 * MINUTE_MS,
    SESSION_DEPOSIT_LIMIT_DEFAULT: 300,
    SESSION_DEPOSIT_LIMIT_MIN: 10,
    SESSION_DEPOSIT_LIMIT_MAX: 2000,
    XP_BASE_PER_SPIN: 8,
    XP_WIN_MULTIPLIER: 4,
    LOSS_ANIMATION_MULTIPLIER: 1,
    WIN_ANIMATION_MULTIPLIER: 1.6,
    PROGRESSIVE_PRECISION: 2,
    CURRENCY_PRECISION: 2,
    PAYOUT_PRECISION: 2,
    RANDOM_FLOAT_DENOMINATOR: 1_000_000,
    SYMBOLS,
    WILD_SYMBOL_ID: "HALLUCINATION",
    SCATTER_SYMBOL_ID: "PROMPT",
    JACKPOT_TRIGGER_SYMBOL_ID: "GPT5",
    JACKPOT_TRIGGER_MATCH_COUNT: 5,
    SCATTER_TRIGGER_COUNT: 3,
    WIN_MESSAGES,
    XP_TIERS,
  },
  CLIENT: {
    AUTOPLAY_MIN_SPINS: 1,
    AUDIO: {
      GAIN_FLOOR: 0.001,
      NEAR_MISS_START_HZ: 220,
      NEAR_MISS_END_HZ: 440,
      NEAR_MISS_ATTACK_SEC: 0.08,
      NEAR_MISS_DURATION_SEC: 0.3,
      NEAR_MISS_GAIN_PEAK: 0.08,
      WIN_FANFARE_NOTES: [330, 440, 660],
      WIN_FANFARE_NOTE_STAGGER_SEC: 0.05,
      WIN_FANFARE_NOTE_ATTACK_SEC: 0.1,
      WIN_FANFARE_NOTE_DECAY_SEC: 0.35,
      NOTE_TAIL_SEC: 0.01,
      WIN_FANFARE_GAIN_MIN: 0.03,
      WIN_FANFARE_GAIN_MAX: 0.2,
      WIN_FANFARE_GAIN_DIVISOR: 400,
      AMBIENT_HZ: 82,
      AMBIENT_GAIN: 0.012,
    },
  },
};

export { CONFIG };
